### ISSUE TITLE
Add a README.md file with a simple description of this repo

### ISSUE THREAD

**Issue by snasirca** [nayema/java-exercises#2]
You need to learn the Markdown syntax for writing documentation. Learn it from this online tutorial: http://www.markdowntutorial.com/

Then use that knowledge to create a README.md file in this repo describing what the purpose of this repo is. Use headings, subheadings, italics, bold words, etc. The `md` extension of the file stands for Markdown.

**Comment by nayema** [comment]
**Completed task**
